version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: rails
    versions:
    - 6.0.3.4
    - 6.0.3.5
  - dependency-name: faker
    versions:
    - 2.15.1
    - 2.16.0
  - dependency-name: database_cleaner
    versions:
    - 1.8.5
    - 2.0.0
  - dependency-name: capybara
    versions:
    - 3.35.1
  - dependency-name: newrelic_rpm
    versions:
    - 6.15.0
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: minitest
    versions:
    - 5.14.3
  - dependency-name: unicorn
    versions:
    - 5.8.0
  - dependency-name: sentry-raven
    versions:
    - 3.1.1
