language: ruby
rvm:
  - 2.0.0
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "bundle exec rake db:create db:migrate db:test:prepare default"
bundler_args: --without development
