FROM buildkite/agent:3-ubuntu

RUN apt-get update && apt-get install -y \
    gnupg \
    make \
    unzip \
    wget \
    curl \
    tar \
    sudo \
    s3cmd \
    libpq-dev \
    software-properties-common \
    ca-certificates

# Install cf cli
RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
RUN echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
RUN sudo apt-get update
RUN sudo apt-get install cf-cli

# Install aws cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
RUN aws --version

# Copy buildkite hooks from elastic-ci-stack-s3-secrets-hooks repo
RUN mkdir /buildkite/s3_secrets
COPY ./buildkite/agents/elastic-ci-stack-s3-secrets-hooks /buildkite/s3_secrets
COPY ./buildkite/agents/hooks /buildkite/hooks/

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    net-tools \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install lsof for waiting for ssh tunnels to bind to their port
RUN apt-get update
RUN apt-get -y install lsof

COPY ./vmware-chain.pem /tmp/vmware-chain.pem
RUN cp /tmp/vmware-chain.pem /etc/ssl/certs

RUN ssh-keyscan github.com >> githubKey
RUN cat githubKey >> /etc/ssh/ssh_known_hosts
RUN rm githubKey

RUN mkdir /buildkite-secrets
COPY ./maintenance_mode_id_rsa /tmp/maintenance_mode_id_rsa
RUN cp /tmp/maintenance_mode_id_rsa /buildkite-secrets/

RUN apt-get install -y --force-yes build-essential git
RUN apt-get install -y libssl-dev libreadline-dev zlib1g-dev

# Install rbenv and ruby-build
RUN git clone https://github.com/sstephenson/rbenv.git /root/.rbenv
RUN git clone https://github.com/sstephenson/ruby-build.git /root/.rbenv/plugins/ruby-build
RUN /root/.rbenv/plugins/ruby-build/install.sh
ENV PATH /root/.rbenv/bin:$PATH
RUN echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh
RUN echo 'eval "$(rbenv init -)"' >> .bashrc

RUN rbenv install 2.6.2
RUN rbenv install 2.6.4
