FROM buildkite/agent:3-ubuntu

RUN apt-get update && apt-get install -y \
    gnupg \
    make \
    unzip \
    wget \
    curl \
    tar \
    sudo \
    s3cmd \
    libpq-dev \
    software-properties-common \
    ca-certificates

# Install cf cli
RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
RUN echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
RUN sudo apt-get update
RUN sudo apt-get install cf-cli

# Install aws cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
RUN aws --version

# Install Ruby 2.6.4
RUN wget -O ruby-install-0.7.0.tar.gz https://github.com/postmodern/ruby-install/archive/v0.7.0.tar.gz && \
    tar -xzvf ruby-install-0.7.0.tar.gz && \
    cd ruby-install-0.7.0/ && \
    sudo make install && \
    ./bin/ruby-install --rubies-dir /opt/rubies ruby 2.6.4
RUN wget -O chruby-0.3.9.tar.gz https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz && \
    tar -xzvf chruby-0.3.9.tar.gz && \
    cd chruby-0.3.9/ && \
    sudo make install && \
    ./scripts/setup.sh

RUN apt-get install rubygems -y

# Copy buildkite hooks from elastic-ci-stack-s3-secrets-hooks repo
RUN mkdir /buildkite/s3_secrets
COPY ./buildkite/agents/elastic-ci-stack-s3-secrets-hooks /buildkite/s3_secrets
COPY ./buildkite/agents/hooks /buildkite/hooks/

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    net-tools \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install lsof for waiting for ssh tunnels to bind to their port
RUN apt-get update
RUN apt-get -y install lsof

COPY ./vmware-chain.pem /tmp/vmware-chain.pem
RUN cp /tmp/vmware-chain.pem /etc/ssl/certs

RUN ssh-keyscan github.com >> githubKey
RUN cat githubKey >> /etc/ssh/ssh_known_hosts
RUN rm githubKey

RUN mkdir /buildkite-secrets
COPY ./maintenance_mode_id_rsa /tmp/maintenance_mode_id_rsa
RUN cp /tmp/maintenance_mode_id_rsa /buildkite-secrets/