#!/bin/bash
# shellcheck source=/dev/null
source /buildkite/s3_secrets/hooks/environment

echo "Running whiteboard environment hooks"
set -euo pipefail

eval "$(ssh-agent -s)"
ssh-add -k /buildkite-secrets/maintenance_mode_id_rsa

